Repository samseburn-project/samseburn-backend, pull requests merged in 2021-12, with the labels that each got.

#4 1주차 진행 여부 선택 api
  src/main/java/shop/fevertime/backend/api/ChallengeHistoryApiController.java
  src/main/java/shop/fevertime/backend/domain/ChallengeHistory.java
  src/main/java/shop/fevertime/backend/domain/FirstWeekMission.java
  src/main/java/shop/fevertime/backend/dto/response/UserCertifiesResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeStatusResponseDto.java
  src/main/java/shop/fevertime/backend/repository/ChallengeHistoryRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
Labels: 기능 추가

#6 유저와 연관된 챌린지 & 재도전하기 api
  src/main/java/shop/fevertime/backend/api/ChallengeHistoryApiController.java
  src/main/java/shop/fevertime/backend/domain/ChallengeHistory.java
  src/main/java/shop/fevertime/backend/domain/ChallengeStatus.java
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeInfoDto.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/test/java/shop/fevertime/backend/domain/ChallengeHistoryTest.java
Labels: 기능 추가

#7 CI/CD: 1.0.0 (유저와 연관된 챌린지 API 수정, 1주차 진행 여부)
  src/main/java/shop/fevertime/backend/api/ChallengeHistoryApiController.java
  src/main/java/shop/fevertime/backend/config/WebConfig.java
  src/main/java/shop/fevertime/backend/domain/ChallengeHistory.java
  src/main/java/shop/fevertime/backend/domain/ChallengeStatus.java
  src/main/java/shop/fevertime/backend/domain/FirstWeekMission.java
  src/main/java/shop/fevertime/backend/dto/response/UserCertifiesResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeInfoDto.java
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeStatusResponseDto.java
  src/main/java/shop/fevertime/backend/repository/ChallengeHistoryRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/service/UserService.java
  src/test/java/shop/fevertime/backend/domain/ChallengeHistoryTest.java
Labels: CI/CD

#8 fix: TetsCase error 수정
  src/test/java/shop/fevertime/backend/domain/ChallengeHistoryTest.java
  src/test/java/shop/fevertime/backend/domain/UserTest.java
Labels: bug

#9 CI/CD : WebConfig 추가
  src/main/java/shop/fevertime/backend/api/ChallengeHistoryApiController.java
  src/main/java/shop/fevertime/backend/config/WebConfig.java
  src/main/java/shop/fevertime/backend/dto/request/ChallengeRequestDto.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeResponseDto.java
  src/main/java/shop/fevertime/backend/repository/CertificationRepository.java
  src/main/java/shop/fevertime/backend/service/CertificationService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: CI/CD

#13 인증 수정 api 추가 (#12)
  src/main/java/shop/fevertime/backend/api/CertificationApiController.java
  src/main/java/shop/fevertime/backend/domain/Certification.java
  src/main/java/shop/fevertime/backend/dto/request/CertiUpdateRequestDto.java
  src/main/java/shop/fevertime/backend/service/CertificationService.java
  src/main/java/shop/fevertime/backend/util/CertificationValidator.java
Labels: 기능 추가

#14 fix: 해당 챌린지 로그인 유저의 참여 기록 GET API, 반환 값 추가 ( #10 )
  src/main/java/shop/fevertime/backend/dto/response/ChallengeUserResponseDto.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
Labels: 기능 개선

#15 CI/CD: 챌린지 인증 수정 API, 로그인한 유저 API 수정
  src/main/java/shop/fevertime/backend/api/CertificationApiController.java
  src/main/java/shop/fevertime/backend/domain/Certification.java
  src/main/java/shop/fevertime/backend/dto/request/CertiUpdateRequestDto.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeUserResponseDto.java
  src/main/java/shop/fevertime/backend/service/CertificationService.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/util/CertificationValidator.java
  src/main/java/shop/fevertime/backend/util/ChallengeValidator.java
Labels: 기능 개선, 기능 추가

#17 fix: 챌린지 리스트 (카테고리별) 페이지네이션 ( #16 )
  src/main/java/shop/fevertime/backend/api/ChallengeApiController.java
  src/main/java/shop/fevertime/backend/repository/ChallengeHistoryRepository.java
  src/main/java/shop/fevertime/backend/repository/ChallengeRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: 기능 개선

#18 CI/CD: 챌린지 리스트 (카테고리별) 페이지네이션 ( #16 ), 챌린지 인증 시간 data form 변경
  src/main/java/shop/fevertime/backend/api/ChallengeApiController.java
  src/main/java/shop/fevertime/backend/dto/response/CertificationResponseDto.java
  src/main/java/shop/fevertime/backend/repository/ChallengeHistoryRepository.java
  src/main/java/shop/fevertime/backend/repository/ChallengeRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: CI/CD

#20 CI/CD: 정렬 제거, 페이지 1번부터 시작 적용
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: CI/CD

#21 Feat/16 challenge list paging
  src/main/java/shop/fevertime/backend/dto/response/ChallengeUserResponseDto.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: 기능 개선

#22 CI/ CD: 참가 신청
  src/main/java/shop/fevertime/backend/dto/response/CertificationResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeUserResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeInfoDto.java
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeResponseDto.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: CI/CD

#23 fix: findByChallengeAndUser Optional 처리
  src/main/java/shop/fevertime/backend/repository/ChallengeHistoryRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
Labels: CI/CD

#27 fix: ChallengeList totalCount 추가
  src/main/java/shop/fevertime/backend/api/ChallengeApiController.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeResponseWithTotalCountDto.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: 기능 개선

#28 CI/CD: ChallengeList totalCount 추가
  src/main/java/shop/fevertime/backend/api/ChallengeApiController.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeResponseWithTotalCountDto.java
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeInfoDto.java
  src/main/java/shop/fevertime/backend/repository/ChallengeRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/util/ChallengeValidator.java
Labels: CI/CD

#30 챌린지 인증 리스트 api 수정
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeStatusResponseDto.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: CI/CD

#35 fix: 챌린지 검색 페이지네이션 ( #32 )
  src/main/java/shop/fevertime/backend/api/ChallengeApiController.java
  src/main/java/shop/fevertime/backend/repository/ChallengeRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: 기능 개선

#36 Feat/32 challenge mission scheduler
  src/main/java/shop/fevertime/backend/repository/ChallengeHistoryRepository.java
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: 기능 추가

#37 CI/CD: 챌린지 스케줄러, 챌린지 검색 페이징
  src/main/java/shop/fevertime/backend/api/ChallengeApiController.java
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeResponseDto.java
  src/main/java/shop/fevertime/backend/repository/ChallengeHistoryRepository.java
  src/main/java/shop/fevertime/backend/repository/ChallengeRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/service/UserService.java
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: CI/CD

#38 fix: challenge Scheduler 서울 시간 설정
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: 기능 개선

#39 CI/CD: EB Time Zone - Seoul 지정
  .ebextensions/00-setup-timezone.config
  .github/workflows/docker.yml
Labels: CI/CD

#40 CI/CD: webhook_slack 연동 / 스케줄러 에러 코드 추가
  build.gradle
  src/main/java/shop/fevertime/backend/util/Scheduler.java
  src/main/resources/application.yml
  src/main/resources/logback-slack.xml
Labels: CI/CD

#41 CI/CD: 스케줄러 코드 수정
  src/main/java/shop/fevertime/backend/util/Scheduler.java
  src/main/resources/application.yml
Labels: CI/CD

#42 CI/CD: 스케줄러 시간 수정
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: CI/CD

#43 CI/CD: 스케줄러 시간 수정
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: CI/CD

#45 CI/CD: 스케줄러 시간 수정 - 런타임 에러 주입
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: CI/CD

#46 CI/CD: Dockerfile TimeZone 설정 추가
  Dockerfile
Labels: CI/CD

#47 CI/CD: 스케줄러 time check in slack
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: CI/CD

#48 CI/CD: 스케줄러 time check in slack
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: CI/CD

#49 CI/CD: 스케줄러 time check in slack
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: CI/CD

#50 CI/CD: 스케줄러 time check in slack
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: CI/CD

#51 CI/CD: webookUri 수정
  src/main/java/shop/fevertime/backend/util/Scheduler.java
  src/main/resources/logback-slack.xml
Labels: CI/CD

#52 CI/CD: webhook 변수 설정
  src/main/java/shop/fevertime/backend/util/Scheduler.java
  src/main/resources/logback-slack.xml
Labels: CI/CD

#53 CI/CD: webhook 변수 설정
  src/main/java/shop/fevertime/backend/util/Scheduler.java
  src/main/resources/logback-slack.xml
Labels: CI/CD

#54 CI/CD: springProperty 추가
  src/main/java/shop/fevertime/backend/util/Scheduler.java
  src/main/resources/logback-slack.xml
Labels: CI/CD

#55 CI/CD: springProperty 추가
  src/main/resources/logback-slack.xml
Labels: CI/CD

#56 CI/CD: springProperty 추가
  src/main/java/shop/fevertime/backend/util/Scheduler.java
  src/main/resources/logback-slack.xml
Labels: CI/CD

#57 CI/CD: webhookUri 직접 입력
  src/main/java/shop/fevertime/backend/util/Scheduler.java
  src/main/resources/logback-slack.xml
Labels: CI/CD
